In [46]:
import numpy as np

random_array = np.random.rand(3, 3)
print("Array:\n", random_array)
print("Shape:", random_array.shape)


Array:
 [[0.19636416 0.59612027 0.6314278 ]
 [0.69322516 0.16082825 0.02178801]
 [0.30456277 0.86499181 0.91861989]]
Shape: (3, 3)


In [52]:
flat=random_array.flatten()
print(flat)

[0.19636416 0.59612027 0.6314278  0.69322516 0.16082825 0.02178801
 0.30456277 0.86499181 0.91861989]


In [54]:
reshape=flat.reshape((3,3))
print(reshape)

[[0.19636416 0.59612027 0.6314278 ]
 [0.69322516 0.16082825 0.02178801]
 [0.30456277 0.86499181 0.91861989]]


In [56]:
idx=[1,3,5]
print(flat[idx])

[0.59612027 0.69322516 0.02178801]
